additionalArguments:
  - --providers.file.filename=/data/traefik-config.yaml
ports:
  web:
    redirectTo: websecure
ingressRoute:
  dashboard:
    enabled: true 
persistence:
  enabled: true
  path: /certs
  size: 128Mi
volumes:
  - mountPath: /data
    name: traefik-config
    type: configMap
