- name: Install cert-manager https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/#5-install-cert-manager
  hosts: 127.0.0.1
  
  tasks:
  - name: Install the CustomResourceDefinition resources separately 
    shell: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml 
  
  - name: create cert-manager namespace
    community.kubernetes.k8s:
      name: traefik 
      api_version: v1
      kind: Namespace
      state: present
  
  - name: add traefik repo
    shell: helm repo add traefik https://helm.traefik.io/traefik
  
  - name: update helm repo
    shell: helm repo update
  
  
  - name: apply traefik config (create secret)
    community.kubernetes.k8s:
      state: present
      src: traefik-config.yaml 
  
  - name: install traefik
    community.kubernetes.helm:
      name: traefik 
      chart_ref: traefik/traefik
      release_namespace: traefik 
      values: "{{ lookup('file', 'traefik-chart-values.yml') | from_yaml }}"
  
  - name: expose dashboard
    shell: kubectl apply -f traefik_dashboard_auth.yml -f traefik-dashboard-ingressroute.yml
  
